# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: saludo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='saludo.proto',
  package='saludo',
  syntax='proto3',
  serialized_pb=_b('\n\x0csaludo.proto\x12\x06saludo\"R\n\rSaludoRequest\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x11\n\tapellido1\x18\x02 \x01(\t\x12\x11\n\tapellido2\x18\x03 \x01(\t\x12\x0b\n\x03\x64ni\x18\x04 \x01(\t\"!\n\x0eSaludoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x86\x01\n\x07Saludar\x12\x39\n\x06Saludo\x12\x15.saludo.SaludoRequest\x1a\x16.saludo.SaludoResponse\"\x00\x12@\n\rSaludoOtraVez\x12\x15.saludo.SaludoRequest\x1a\x16.saludo.SaludoResponse\"\x00\x42\x30\n\x19\x65s.giiis.aos.grpc.saludosB\x0bSaludoProtoP\x01\xa2\x02\x03SLDb\x06proto3')
)




_SALUDOREQUEST = _descriptor.Descriptor(
  name='SaludoRequest',
  full_name='saludo.SaludoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nombre', full_name='saludo.SaludoRequest.nombre', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='apellido1', full_name='saludo.SaludoRequest.apellido1', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='apellido2', full_name='saludo.SaludoRequest.apellido2', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dni', full_name='saludo.SaludoRequest.dni', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=106,
)


_SALUDORESPONSE = _descriptor.Descriptor(
  name='SaludoResponse',
  full_name='saludo.SaludoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='saludo.SaludoResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=141,
)

DESCRIPTOR.message_types_by_name['SaludoRequest'] = _SALUDOREQUEST
DESCRIPTOR.message_types_by_name['SaludoResponse'] = _SALUDORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SaludoRequest = _reflection.GeneratedProtocolMessageType('SaludoRequest', (_message.Message,), dict(
  DESCRIPTOR = _SALUDOREQUEST,
  __module__ = 'saludo_pb2'
  # @@protoc_insertion_point(class_scope:saludo.SaludoRequest)
  ))
_sym_db.RegisterMessage(SaludoRequest)

SaludoResponse = _reflection.GeneratedProtocolMessageType('SaludoResponse', (_message.Message,), dict(
  DESCRIPTOR = _SALUDORESPONSE,
  __module__ = 'saludo_pb2'
  # @@protoc_insertion_point(class_scope:saludo.SaludoResponse)
  ))
_sym_db.RegisterMessage(SaludoResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\031es.giiis.aos.grpc.saludosB\013SaludoProtoP\001\242\002\003SLD'))

_SALUDAR = _descriptor.ServiceDescriptor(
  name='Saludar',
  full_name='saludo.Saludar',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=144,
  serialized_end=278,
  methods=[
  _descriptor.MethodDescriptor(
    name='Saludo',
    full_name='saludo.Saludar.Saludo',
    index=0,
    containing_service=None,
    input_type=_SALUDOREQUEST,
    output_type=_SALUDORESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SaludoOtraVez',
    full_name='saludo.Saludar.SaludoOtraVez',
    index=1,
    containing_service=None,
    input_type=_SALUDOREQUEST,
    output_type=_SALUDORESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SALUDAR)

DESCRIPTOR.services_by_name['Saludar'] = _SALUDAR

# @@protoc_insertion_point(module_scope)
